#!usr/bin/env bash
#configuring web-01 to have an HTTP reponse header

#updating packages
sudo apt-get updates
sudo apt-get install -y nginx

#creating an index page
echo "hello world!" | sudo tee /var/www/html/index.html

#performing a redirection
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/alpheus-tema permanent;"

sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

#creating a custom error page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# custom HTTP reponse header

sudo sed -i "server_name _;/a add_header x-served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

#test for syntax errors
sudo nginx -t

#restart nginx
sudo service nginx restart
